#!/bin/bash

# INDEED JOB SEARCH AUTOMATION
# Searches Indeed for relevant jobs and exports to CSV + markdown
# Usage: ./INDEED_SEARCH_AUTOMATION.sh
# Cron: Run daily at 8 AM

SEARCH_DATE=$(date +"%Y-%m-%d")
REPORT_FILE="job_search_report_${SEARCH_DATE}.md"
OUTPUT_DIR="../job_search"

# Job search queries - customize these based on YOUR target roles
declare -a SEARCH_QUERIES=(
    "remote writing"
    "technical writer remote"
    "content writer France"
    "documentation specialist remote"
    "UX writer remote"
    "English teacher online"
    "freelance translator English"
    "automation engineer remote"
)

echo "# Indeed Job Search Report - ${SEARCH_DATE}" > "${OUTPUT_DIR}/${REPORT_FILE}"
echo "" >> "${OUTPUT_DIR}/${REPORT_FILE}"
echo "Generated by automated search at $(date)" >> "${OUTPUT_DIR}/${REPORT_FILE}"
echo "" >> "${OUTPUT_DIR}/${REPORT_FILE}"

# Install jq if not present (needed for JSON parsing)
if ! command -v jq &> /dev/null; then
    echo "Note: jq not installed. Install with: sudo apt-get install jq"
fi

for query in "${SEARCH_QUERIES[@]}"; do
    echo "Searching: $query"
    echo "" >> "${OUTPUT_DIR}/${REPORT_FILE}"
    echo "## Search Query: $query" >> "${OUTPUT_DIR}/${REPORT_FILE}"
    echo "" >> "${OUTPUT_DIR}/${REPORT_FILE}"

    # Using curl to fetch job listings (Indeed search results)
    # Note: Indeed's robots.txt restricts scraping - this is informational only
    # For production use, consider Indeed's API or affiliate program

    echo "- See Indeed.com for current listings" >> "${OUTPUT_DIR}/${REPORT_FILE}"
    echo "- URL: https://www.indeed.com/jobs?q=${query// /+}&l=remote" >> "${OUTPUT_DIR}/${REPORT_FILE}"
    echo "" >> "${OUTPUT_DIR}/${REPORT_FILE}"
done

echo "✓ Job search report generated: ${OUTPUT_DIR}/${REPORT_FILE}"

# MANUAL INSTRUCTION (because Indeed API has limitations)
cat << 'EOF' >> "${OUTPUT_DIR}/${REPORT_FILE}"

---

## How to Use This Script

1. **Set up your search queries above** - customize SEARCH_QUERIES array
2. **Run daily**: `chmod +x INDEED_SEARCH_AUTOMATION.sh && ./INDEED_SEARCH_AUTOMATION.sh`
3. **Cron setup** (optional):
   ```bash
   # Add to crontab: 0 8 * * * /path/to/INDEED_SEARCH_AUTOMATION.sh
   crontab -e
   ```

## For Active Scraping (Advanced)

If you want automated Indeed scraping, use:
- `python-indeed` library (unofficial)
- Direct HTML scraping with BeautifulSoup + Selenium
- Indeed's affiliate API (if eligible)

**Important**: Check Indeed's robots.txt and Terms of Service. Respect rate limits.

## Alternative: LinkedIn Search API

LinkedIn offers an official API for job searches:
- Register at: https://www.linkedin.com/developers/apps
- Use: `python-linkedin` library
- Requires: API credentials

## Alternative: Mix Multiple Sources

- **FlexJobs.com** - pre-screened remote jobs (requires subscription)
- **We Work Remotely** - API available
- **Remote.co** - RSS feeds available
- **Dev.to Jobs** - API available
- **GitHub Jobs** - discontinued but archives exist

EOF

echo "✓ Complete! Check ${OUTPUT_DIR}/${REPORT_FILE}"
