#!/usr/bin/env python3
"""
job_hunt_automation.py  —  Automated Job Search

Searches for jobs and emails a daily digest.

Usage:
  export ZOHO_USER=your@zohomail.com
  export ZOHO_PASS=your-app-password
  python3 job_hunt_automation.py

Cron (daily 8 AM):
  0 8 * * * /usr/bin/python3 /path/to/job_hunt_automation.py

Install:
  pip install requests beautifulsoup4 lxml
"""

import os
import smtplib
import ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import requests
from datetime import date

try:
    from bs4 import BeautifulSoup
except ImportError:
    BeautifulSoup = None


ZOHO_USER  = os.environ.get('ZOHO_USER',  '')
ZOHO_PASS  = os.environ.get('ZOHO_PASS',  '')
TO_EMAIL   = os.environ.get('TO_EMAIL',   ZOHO_USER)

# Job search configuration
JOB_SEARCHES = [
    {'query': 'English teacher ELT',   'location': 'Reunion'},
    {'query': 'CELTA teacher',          'location': 'France'},
    {'query': 'EFL ESL instructor',     'location': 'Remote'},
    {'query': 'English language tutor', 'location': 'Mauritius'},
]


# ---------------------------------------------------------------------------
# Indeed RSS (no API key needed)
# ---------------------------------------------------------------------------

def fetch_indeed_rss(query: str, location: str, max_results: int = 5) -> list:
    """Fetch jobs from Indeed RSS feed."""
    if BeautifulSoup is None:
        return []

    url = (
        f'https://rss.indeed.com/rss?'
        f'q={requests.utils.quote(query)}&'
        f'l={requests.utils.quote(location)}&'
        f'sort=date'
    )

    try:
        r = requests.get(url, timeout=20,
                         headers={'User-Agent': 'Mozilla/5.0'})
        r.raise_for_status()
        soup  = BeautifulSoup(r.content, 'lxml-xml')
        items = soup.find_all('item')[:max_results]

        jobs = []
        for item in items:
            jobs.append({
                'title':    item.find('title').text if item.find('title') else 'No title',
                'link':     item.find('link').text  if item.find('link')  else '#',
                'company':  (item.find('source') or item.find('author') or
                             item.find('description') or item).text[:60],
                'summary':  (item.find('description').text[:200]
                             if item.find('description') else ''),
                'date':     item.find('pubDate').text if item.find('pubDate') else '',
            })
        return jobs
    except Exception as e:
        print(f'Indeed RSS error ({query} / {location}): {e}')
        return []


# ---------------------------------------------------------------------------
# Build HTML digest
# ---------------------------------------------------------------------------

def build_email_html(all_results: dict) -> str:
    today = date.today().strftime('%A %d %B %Y')
    sections = []

    for search_key, jobs in all_results.items():
        if not jobs:
            continue
        rows = ''.join(
            f'<tr>'
            f'<td style="padding:8px;border-bottom:1px solid #eee;">'
            f'<a href="{j["link"]}" style="color:#0e639c;">{j["title"]}</a><br/>'
            f'<small style="color:#666;">{j["summary"][:150]}</small>'
            f'</td>'
            f'<td style="padding:8px;border-bottom:1px solid #eee;color:#666;font-size:12px;">'
            f'{j["date"][:16]}'
            f'</td>'
            f'</tr>'
            for j in jobs
        )
        sections.append(
            f'<h3 style="color:#333;margin-top:20px;">{search_key}</h3>'
            f'<table style="width:100%;border-collapse:collapse;font-family:sans-serif;font-size:14px;">'
            f'{rows}</table>'
        )

    if not sections:
        return '<p>No new jobs found today.</p>'

    return f"""
    <html><body style="max-width:700px;margin:auto;font-family:sans-serif;">
    <h2 style="color:#673de6;">Daily Job Digest — {today}</h2>
    {''.join(sections)}
    <hr/><p style="color:#999;font-size:12px;">Auto-generated by job_hunt_automation.py</p>
    </body></html>
    """


# ---------------------------------------------------------------------------
# Send email via Zoho
# ---------------------------------------------------------------------------

def send_email(subject: str, html_body: str):
    if not ZOHO_USER or not ZOHO_PASS:
        print('Email not configured. Set ZOHO_USER and ZOHO_PASS.')
        print(html_body[:500])
        return

    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From']    = ZOHO_USER
    msg['To']      = TO_EMAIL
    msg.attach(MIMEText(html_body, 'html'))

    context = ssl.create_default_context()
    try:
        with smtplib.SMTP('smtp.zoho.com', 587) as server:
            server.starttls(context=context)
            server.login(ZOHO_USER, ZOHO_PASS)
            server.sendmail(ZOHO_USER, TO_EMAIL, msg.as_string())
        print(f'Email sent to {TO_EMAIL}')
    except Exception as e:
        print(f'Email error: {e}')


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print(f'Searching for jobs ({date.today()})...')
    all_results = {}

    for search in JOB_SEARCHES:
        key  = f"{search['query']} in {search['location']}"
        jobs = fetch_indeed_rss(search['query'], search['location'])
        all_results[key] = jobs
        print(f'  {key}: {len(jobs)} results')

    total = sum(len(j) for j in all_results.values())
    if total == 0:
        print('No jobs found today. No email sent.')
        return

    html    = build_email_html(all_results)
    today   = date.today().strftime('%d %b %Y')
    subject = f'Job Digest {today} — {total} new listings'

    send_email(subject, html)


if __name__ == '__main__':
    main()
