#!/usr/bin/env python3
"""
job_search.py

Searches Indeed RSS feeds for ELT/TEFL/CELTA jobs and
emails a daily digest.

Install:   pip install requests beautifulsoup4 lxml
Cron:      0 8 * * * /usr/bin/python3 /path/to/scripts/job_search.py

Environment variables:
    SMTP_HOST      e.g. smtp.zoho.com
    SMTP_PORT      587
    SMTP_USER      your email
    SMTP_PASS      your email password or app password
    ALERT_EMAIL    where to send the digest
"""

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

try:
    import requests
    from bs4 import BeautifulSoup
except ImportError:
    print('Run: pip install requests beautifulsoup4 lxml')
    exit(1)

# ── Configuration ────────────────────────────────────────────────────────────
SMTP_HOST   = os.environ.get('SMTP_HOST',   'smtp.zoho.com')
SMTP_PORT   = int(os.environ.get('SMTP_PORT', '587'))
SMTP_USER   = os.environ.get('SMTP_USER',   '')
SMTP_PASS   = os.environ.get('SMTP_PASS',   '')
ALERT_EMAIL = os.environ.get('ALERT_EMAIL', 'sourovdeb@zohomail.com')

# Indeed RSS feed URLs (no API key needed)
SEARCHES = [
    {'label': 'ELT Teacher – Reunion',    'url': 'https://rss.indeed.com/rss?q=ELT+teacher&l=Reunion'},
    {'label': 'TEFL Teacher – Worldwide', 'url': 'https://rss.indeed.com/rss?q=TEFL+teacher'},
    {'label': 'CELTA – Worldwide',        'url': 'https://rss.indeed.com/rss?q=CELTA'},
    {'label': 'English Teacher Online',    'url': 'https://rss.indeed.com/rss?q=online+English+teacher'},
    {'label': 'ELT Content Writer',        'url': 'https://rss.indeed.com/rss?q=ELT+content+writer'},
]


def fetch_jobs(search_url, label, max_results=5):
    jobs = []
    try:
        resp = requests.get(search_url, timeout=15,
                            headers={'User-Agent': 'Mozilla/5.0'})
        soup = BeautifulSoup(resp.content, 'xml')
        items = soup.find_all('item')[:max_results]
        for item in items:
            title    = item.title.text.strip()   if item.title   else 'No title'
            link     = item.link.text.strip()    if item.link    else ''
            pub_date = item.pubDate.text.strip() if item.pubDate else ''
            desc_raw = item.description.text     if item.description else ''
            # Strip HTML from description
            desc_soup = BeautifulSoup(desc_raw, 'html.parser')
            summary = desc_soup.get_text()[:200].strip()
            jobs.append({'title': title, 'link': link, 'date': pub_date,
                         'summary': summary, 'source': label})
    except Exception as e:
        print(f'  Error fetching {label}: {e}')
    return jobs


def build_email_html(all_jobs):
    if not all_jobs:
        return '<p>No new job listings found today.</p>'

    sections = []
    by_source = {}
    for job in all_jobs:
        by_source.setdefault(job['source'], []).append(job)

    for source, jobs in by_source.items():
        items_html = ''.join(
            f'<li style="margin-bottom:12px;">'
            f'<a href="{j["link"]}" style="color:#0e639c;font-weight:bold;">{j["title"]}</a><br>'
            f'<span style="color:#666;font-size:12px;">{j["date"]}</span><br>'
            f'<span style="font-size:13px;">{j["summary"]}...</span>'
            f'</li>'
            for j in jobs
        )
        sections.append(
            f'<h3 style="color:#333;border-bottom:1px solid #eee;padding-bottom:4px;">{source}</h3>'
            f'<ul style="list-style:none;padding:0;">{items_html}</ul>'
        )

    return f'''
    <div style="font-family:sans-serif;max-width:600px;margin:0 auto;">
        <h2 style="color:#1e1e1e;">Daily Job Digest — {datetime.now().strftime("%d %B %Y")}</h2>
        {chr(10).join(sections)}
        <p style="color:#888;font-size:11px;">Generated by job_search.py — sourovdeb/my_professional_documents</p>
    </div>
    '''


def send_email(subject, html_body):
    if not SMTP_USER or not SMTP_PASS:
        print('SMTP credentials not set. Printing digest instead:\n')
        # Fallback: print to console
        from bs4 import BeautifulSoup as BS
        print(BS(html_body, 'html.parser').get_text())
        return

    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From']    = SMTP_USER
    msg['To']      = ALERT_EMAIL
    msg.attach(MIMEText(html_body, 'html'))

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASS)
            server.send_message(msg)
        print(f'Digest sent to {ALERT_EMAIL}')
    except Exception as e:
        print(f'Email error: {e}')


def main():
    print(f'Searching for ELT/TEFL jobs...  ({datetime.now().strftime("%Y-%m-%d %H:%M")})')
    all_jobs = []
    for search in SEARCHES:
        print(f'  Checking: {search["label"]}')
        jobs = fetch_jobs(search['url'], search['label'])
        all_jobs.extend(jobs)
        print(f'  Found {len(jobs)} listings')

    print(f'Total: {len(all_jobs)} jobs found')
    html = build_email_html(all_jobs)
    subject = f'Daily Job Digest: {len(all_jobs)} ELT listings — {datetime.now().strftime("%d %b %Y")}'
    send_email(subject, html)


if __name__ == '__main__':
    main()
