#!/usr/bin/env python3
"""
Job Search Automation — Sourov Deb
Searches Indeed RSS + sends digest email via Gmail SMTP.
Free. Open source. No paid APIs needed.

Dependencies: pip install requests beautifulsoup4 feedparser
"""

import feedparser
import smtplib
import json
import os
from datetime import datetime, timedelta
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

# ── CONFIG ────────────────────────────────────────────────────────────────────
CONFIG = {
    "email_to": "sourovdeb.is@gmail.com",
    "email_from": "sourovdeb.is@gmail.com",
    "app_password": os.getenv("GMAIL_APP_PASSWORD", ""),  # Set env var
    "search_queries": [
        # English teaching / TEFL
        "English+teacher+La+Reunion",
        "IELTS+teacher+remote",
        "English+language+trainer+remote",
        # Hospitality / Management
        "hotel+manager+Reunion+Island",
        "hospitality+manager+French+overseas",
        # Writing / Content
        "content+writer+mental+health+remote",
        "freelance+writer+neurodiversity+remote",
        # Education
        "adult+education+trainer+remote",
    ],
    "days_back": 3,  # Only show jobs from last N days
    "log_file": "job_search_log.json",
}

INDEED_RSS = "https://www.indeed.com/rss?q={query}&sort=date"
REMOTE_OK_RSS = "https://remoteok.com/remote-jobs.rss"


def fetch_indeed_jobs(query: str, days_back: int) -> list[dict]:
    """Fetch jobs from Indeed RSS feed."""
    url = INDEED_RSS.format(query=query)
    feed = feedparser.parse(url)
    cutoff = datetime.now() - timedelta(days=days_back)
    jobs = []
    for entry in feed.entries:
        try:
            pub = datetime(*entry.published_parsed[:6])
            if pub < cutoff:
                continue
        except Exception:
            pass
        jobs.append({
            "title": entry.get("title", ""),
            "company": entry.get("author", "Unknown"),
            "location": entry.get("location", ""),
            "url": entry.get("link", ""),
            "summary": entry.get("summary", "")[:300],
            "date": entry.get("published", ""),
            "source": "Indeed",
            "query": query,
        })
    return jobs


def deduplicate(jobs: list[dict]) -> list[dict]:
    """Remove duplicate jobs by URL."""
    seen = set()
    unique = []
    for job in jobs:
        if job["url"] not in seen:
            seen.add(job["url"])
            unique.append(job)
    return unique


def build_email_html(jobs: list[dict]) -> str:
    """Build a clean HTML digest email."""
    date_str = datetime.now().strftime("%A %d %B %Y")
    rows = ""
    for j in jobs:
        rows += f"""
        <tr>
          <td style="padding:8px;border-bottom:1px solid #eee;">
            <strong><a href="{j['url']}" style="color:#1a73e8;text-decoration:none;">{j['title']}</a></strong><br>
            <span style="color:#555;">{j.get('company','')} — {j.get('location','Remote')}</span><br>
            <small style="color:#888;">{j.get('date','')} | {j.get('source','')} | Query: {j.get('query','')}</small>
          </td>
        </tr>"""
    return f"""
    <html><body style="font-family:Arial,sans-serif;max-width:700px;margin:auto;">
      <h2 style="color:#333;">Job Digest — {date_str}</h2>
      <p>{len(jobs)} new job(s) found in the last {CONFIG['days_back']} days.</p>
      <table width="100%" cellspacing="0">{rows}</table>
      <hr><p style="color:#aaa;font-size:12px;">Auto-generated by Sourov's job search bot.</p>
    </body></html>"""


def send_email(subject: str, html_body: str) -> None:
    """Send email via Gmail SMTP with app password."""
    if not CONFIG["app_password"]:
        print("⚠  Set GMAIL_APP_PASSWORD env var to send email.")
        print(f"📧 Would send: {subject}")
        return
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = CONFIG["email_from"]
    msg["To"] = CONFIG["email_to"]
    msg.attach(MIMEText(html_body, "html"))
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(CONFIG["email_from"], CONFIG["app_password"])
        server.sendmail(CONFIG["email_from"], CONFIG["email_to"], msg.as_string())
    print(f"✅ Email sent: {subject}")


def log_jobs(jobs: list[dict]) -> None:
    """Append new jobs to a JSON log file."""
    existing = []
    if os.path.exists(CONFIG["log_file"]):
        with open(CONFIG["log_file"]) as f:
            existing = json.load(f)
    existing_urls = {j["url"] for j in existing}
    new_jobs = [j for j in jobs if j["url"] not in existing_urls]
    with open(CONFIG["log_file"], "w") as f:
        json.dump(existing + new_jobs, f, indent=2)
    print(f"📝 Logged {len(new_jobs)} new unique jobs.")


def run():
    print(f"🔍 Starting job search — {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    all_jobs = []
    for query in CONFIG["search_queries"]:
        jobs = fetch_indeed_jobs(query, CONFIG["days_back"])
        print(f"  ↳ '{query}': {len(jobs)} results")
        all_jobs.extend(jobs)
    all_jobs = deduplicate(all_jobs)
    print(f"✅ {len(all_jobs)} unique jobs found.")
    log_jobs(all_jobs)
    if all_jobs:
        html = build_email_html(all_jobs)
        send_email(f"Job Digest — {len(all_jobs)} new jobs — {datetime.now().strftime('%d %b %Y')}", html)
    else:
        print("ℹ  No new jobs today.")


if __name__ == "__main__":
    run()
